// FastMD installer (plan 5.4): one small exe that carries the program inside itself.
//
// Per-user, no administrator: everything goes to %LOCALAPPDATA%\Programs\FastMD, the shortcut to the user's Start
// menu, the uninstall entry to HKCU. No MSI, no MSIX (its AppData virtualisation slows file I/O by 1.3-2.4x, see
// REPORT.md), no service, no scheduled task, nothing left running.
//
//   FastMD-Setup.exe                install, asking first
//   FastMD-Setup.exe /S             install without asking (used by the updater)
//   FastMD-Setup.exe /noassoc       install without touching the .md association
//   FastMD-Setup.exe /uninstall     remove it again (this is what the entry in "Apps" runs)
//   FastMD-Setup.exe /uninstall /S  the same, silently
//
// The files are RCDATA resources put in by the build (setup_payload.rc, generated by CMake).
#include <windows.h>
#include <commctrl.h>
#include <shellapi.h>
#include <shlobj.h>
#include <shlwapi.h>

#include <string>
#include <vector>

#include "setup_payload.h"  // generated: kPayload[] = { id, file name }
#include "version.h"        // generated: FASTMD_VERSION_STR

namespace {
const wchar_t* kAppName = L"FastMD";
const wchar_t* kUninstallKey = L"Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\FastMD";
const wchar_t* kPublisher = L"FastMD";
const wchar_t* kHomepage = L"https://github.com/beanbo/FastMD";

bool g_silent = false;
bool g_noAssoc = false;
bool g_moved = false;  // the uninstaller is the copy in %TEMP%, not the one inside the install folder

std::wstring KnownDir(REFKNOWNFOLDERID id) {
    PWSTR p = nullptr;
    std::wstring out;
    if (SUCCEEDED(SHGetKnownFolderPath(id, 0, nullptr, &p)) && p) out = p;
    if (p) CoTaskMemFree(p);
    return out;
}

std::wstring InstallDir() {
    std::wstring local = KnownDir(FOLDERID_LocalAppData);
    return local.empty() ? L"" : local + L"\\Programs\\FastMD";
}

std::wstring ShortcutPath() {
    std::wstring menu = KnownDir(FOLDERID_Programs);
    return menu.empty() ? L"" : menu + L"\\FastMD.lnk";
}

void Say(const wchar_t* title, const wchar_t* text, bool error = false) {
    if (g_silent) return;
    MessageBoxW(nullptr, text, title, MB_OK | (error ? MB_ICONERROR : MB_ICONINFORMATION));
}

bool Ask(const std::wstring& dir, BOOL* associate) {
    if (g_silent) return true;
    TASKDIALOGCONFIG c{sizeof(c)};
    std::wstring content = L"Папка: " + dir + L"\n\nПрава администратора не нужны: программа ставится только для вас.";
    c.hwndParent = nullptr;
    c.dwCommonButtons = TDCBF_CANCEL_BUTTON;
    c.pszWindowTitle = L"Установка FastMD";
    c.pszMainIcon = TD_INFORMATION_ICON;
    c.pszMainInstruction = L"Установить FastMD " FASTMD_VERSION_WSTR L"?";
    c.pszContent = content.c_str();
    c.pszVerificationText = L"Открывать файлы .md в FastMD";
    c.dwFlags = TDF_VERIFICATION_FLAG_CHECKED | TDF_POSITION_RELATIVE_TO_WINDOW;
    TASKDIALOG_BUTTON buttons[] = {{IDOK, L"Установить"}};
    c.pButtons = buttons;
    c.cButtons = 1;
    int pressed = 0;
    if (FAILED(TaskDialogIndirect(&c, &pressed, nullptr, associate))) {  // no comctl6: plain question instead
        *associate = TRUE;
        return MessageBoxW(nullptr, content.c_str(), L"Установить FastMD?", MB_OKCANCEL | MB_ICONQUESTION) == IDOK;
    }
    return pressed == IDOK;
}

bool WriteResourceFile(int id, const std::wstring& path) {
    HRSRC res = FindResourceW(nullptr, MAKEINTRESOURCEW(id), RT_RCDATA);
    if (!res) return false;
    HGLOBAL h = LoadResource(nullptr, res);
    const void* data = h ? LockResource(h) : nullptr;
    DWORD size = SizeofResource(nullptr, res);
    if (!data || !size) return false;
    // a running copy cannot be overwritten, but it can be renamed out of the way (publish.ps1 does the same)
    if (GetFileAttributesW(path.c_str()) != INVALID_FILE_ATTRIBUTES) {
        std::wstring old = path + L".old";
        DeleteFileW(old.c_str());
        if (!DeleteFileW(path.c_str())) MoveFileExW(path.c_str(), old.c_str(), MOVEFILE_REPLACE_EXISTING);
    }
    HANDLE f = CreateFileW(path.c_str(), GENERIC_WRITE, 0, nullptr, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
    if (f == INVALID_HANDLE_VALUE) return false;
    DWORD wrote = 0;
    bool ok = WriteFile(f, data, size, &wrote, nullptr) && wrote == size;
    CloseHandle(f);
    return ok;
}

bool MakeShortcut(const std::wstring& target, const std::wstring& link) {
    IShellLinkW* sl = nullptr;
    if (FAILED(CoCreateInstance(CLSID_ShellLink, nullptr, CLSCTX_INPROC_SERVER, IID_PPV_ARGS(&sl)))) return false;
    sl->SetPath(target.c_str());
    sl->SetDescription(L"Мгновенный просмотр Markdown");
    sl->SetIconLocation(target.c_str(), 0);
    std::wstring dir = target.substr(0, target.find_last_of(L'\\'));
    sl->SetWorkingDirectory(dir.c_str());
    IPersistFile* pf = nullptr;
    bool ok = false;
    if (SUCCEEDED(sl->QueryInterface(IID_PPV_ARGS(&pf)))) {
        ok = SUCCEEDED(pf->Save(link.c_str(), TRUE));
        pf->Release();
    }
    sl->Release();
    return ok;
}

void SetRegString(HKEY k, const wchar_t* name, const std::wstring& v) {
    RegSetValueExW(k, name, 0, REG_SZ, (const BYTE*)v.c_str(), (DWORD)((v.size() + 1) * sizeof(wchar_t)));
}

uint64_t DirSizeKb(const std::wstring& dir) {
    uint64_t total = 0;
    WIN32_FIND_DATAW fd{};
    HANDLE h = FindFirstFileW((dir + L"\\*").c_str(), &fd);
    if (h == INVALID_HANDLE_VALUE) return 0;
    do {
        if (!(fd.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY))
            total += ((uint64_t)fd.nFileSizeHigh << 32) | fd.nFileSizeLow;
    } while (FindNextFileW(h, &fd));
    FindClose(h);
    return total / 1024;
}

void RunAndWait(const std::wstring& exe, const std::wstring& args, bool wait) {
    std::wstring cmd = L"\"" + exe + L"\" " + args;
    STARTUPINFOW si{sizeof(si)};
    PROCESS_INFORMATION pi{};
    if (!CreateProcessW(nullptr, cmd.data(), nullptr, nullptr, FALSE, 0, nullptr, nullptr, &si, &pi)) return;
    if (wait) WaitForSingleObject(pi.hProcess, 20000);
    CloseHandle(pi.hThread);
    CloseHandle(pi.hProcess);
}

int Install() {
    std::wstring dir = InstallDir();
    if (dir.empty()) {
        Say(L"FastMD", L"Не удалось найти папку профиля пользователя.", true);
        return 1;
    }
    BOOL associate = g_noAssoc ? FALSE : TRUE;
    if (!Ask(dir, &associate)) return 2;
    if (g_noAssoc) associate = FALSE;
    SHCreateDirectoryExW(nullptr, dir.c_str(), nullptr);
    for (const auto& p : kPayload) {
        if (!WriteResourceFile(p.id, dir + L"\\" + p.name)) {
            Say(L"FastMD", (L"Не удалось записать файл: " + std::wstring(p.name)).c_str(), true);
            return 1;
        }
    }
    std::wstring exe = dir + L"\\FastMD.exe";
    std::wstring setup = dir + L"\\FastMD-Setup.exe";
    wchar_t self[MAX_PATH];
    if (GetModuleFileNameW(nullptr, self, MAX_PATH)) CopyFileW(self, setup.c_str(), FALSE);  // for uninstalling later

    MakeShortcut(exe, ShortcutPath());

    HKEY k = nullptr;
    if (RegCreateKeyExW(HKEY_CURRENT_USER, kUninstallKey, 0, nullptr, 0, KEY_WRITE, nullptr, &k, nullptr) ==
        ERROR_SUCCESS) {
        SetRegString(k, L"DisplayName", kAppName);
        SetRegString(k, L"DisplayVersion", FASTMD_VERSION_WSTR);
        SetRegString(k, L"Publisher", kPublisher);
        SetRegString(k, L"InstallLocation", dir);
        SetRegString(k, L"DisplayIcon", exe);
        SetRegString(k, L"UninstallString", L"\"" + setup + L"\" /uninstall");
        SetRegString(k, L"QuietUninstallString", L"\"" + setup + L"\" /uninstall /S");
        SetRegString(k, L"URLInfoAbout", kHomepage);
        DWORD one = 1, size = (DWORD)DirSizeKb(dir);
        RegSetValueExW(k, L"NoModify", 0, REG_DWORD, (const BYTE*)&one, sizeof(one));
        RegSetValueExW(k, L"NoRepair", 0, REG_DWORD, (const BYTE*)&one, sizeof(one));
        RegSetValueExW(k, L"EstimatedSize", 0, REG_DWORD, (const BYTE*)&size, sizeof(size));
        RegCloseKey(k);
    }
    if (associate) {
        RunAndWait(exe, L"--register-quiet", true);     // .md handler in HKCU, no dialog
        RunAndWait(exe, L"--register-preview", true);   // and the preview pane in Explorer
    }
    if (!g_silent) {
        Say(L"FastMD", (L"FastMD " FASTMD_VERSION_WSTR L" установлен.\n\n" + dir +
                        L"\n\nЯрлык добавлен в меню «Пуск». Удалить можно в «Параметры → Приложения».")
                           .c_str());
        RunAndWait(exe, L"", false);
    }
    return 0;
}

void DeleteDirRecursive(const std::wstring& dir) {
    WIN32_FIND_DATAW fd{};
    HANDLE h = FindFirstFileW((dir + L"\\*").c_str(), &fd);
    if (h != INVALID_HANDLE_VALUE) {
        do {
            std::wstring name = fd.cFileName;
            if (name == L"." || name == L"..") continue;
            std::wstring full = dir + L"\\" + name;
            if (fd.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) DeleteDirRecursive(full);
            else DeleteFileW(full.c_str());
        } while (FindNextFileW(h, &fd));
        FindClose(h);
    }
    RemoveDirectoryW(dir.c_str());
}

int Uninstall() {
    std::wstring dir = InstallDir();
    // The uninstaller cannot delete the folder it is running from, so it moves itself out first: a copy in %TEMP%
    // does the work and then asks Windows to remove that copy at the next boot.
    wchar_t self[MAX_PATH] = L"";
    GetModuleFileNameW(nullptr, self, MAX_PATH);
    if (!g_moved && StrStrIW(self, dir.c_str()) == self) {
        wchar_t tmp[MAX_PATH];
        if (GetTempPathW(MAX_PATH, tmp)) {
            std::wstring copy = std::wstring(tmp) + L"FastMD-Uninstall.exe";
            if (CopyFileW(self, copy.c_str(), FALSE)) {
                RunAndWait(copy, g_silent ? L"/uninstall /S /moved" : L"/uninstall /moved", false);
                return 0;
            }
        }
    }
    if (!g_silent && MessageBoxW(nullptr, L"Удалить FastMD?\n\nНастройки и позиции чтения останутся в профиле.",
                                 L"FastMD", MB_OKCANCEL | MB_ICONQUESTION) != IDOK)
        return 2;
    std::wstring exe = dir + L"\\FastMD.exe";
    // give the .md association back only if it points at the copy being removed: another copy may own it
    wchar_t cmd[1024] = L"";
    DWORD n = sizeof(cmd) - sizeof(wchar_t);
    bool ours = RegGetValueW(HKEY_CURRENT_USER, L"Software\\Classes\\FastMD.Markdown\\shell\\open\\command", nullptr,
                             RRF_RT_REG_SZ, nullptr, cmd, &n) == ERROR_SUCCESS &&
                StrStrIW(cmd, dir.c_str()) != nullptr;
    if (ours && GetFileAttributesW(exe.c_str()) != INVALID_FILE_ATTRIBUTES) RunAndWait(exe, L"--unregister", true);
    if (GetFileAttributesW(exe.c_str()) != INVALID_FILE_ATTRIBUTES) RunAndWait(exe, L"--unregister-preview", true);
    DeleteFileW(ShortcutPath().c_str());
    RegDeleteKeyW(HKEY_CURRENT_USER, kUninstallKey);
    DeleteDirRecursive(dir);                                   // the whole install folder, setup exe included
    MoveFileExW(self, nullptr, MOVEFILE_DELAY_UNTIL_REBOOT);   // and this copy in %TEMP% at the next boot
    Say(L"FastMD", L"FastMD удалён.");
    return 0;
}
}  // namespace

int WINAPI wWinMain(HINSTANCE, HINSTANCE, PWSTR, int) {
    bool uninstall = false;
    int argc = 0;
    if (LPWSTR* argv = CommandLineToArgvW(GetCommandLineW(), &argc)) {
        for (int i = 1; i < argc; i++) {
            std::wstring a = argv[i];
            if (_wcsicmp(a.c_str(), L"/S") == 0 || _wcsicmp(a.c_str(), L"/silent") == 0) g_silent = true;
            else if (_wcsicmp(a.c_str(), L"/uninstall") == 0 || _wcsicmp(a.c_str(), L"/u") == 0) uninstall = true;
            else if (_wcsicmp(a.c_str(), L"/noassoc") == 0) g_noAssoc = true;
            else if (_wcsicmp(a.c_str(), L"/moved") == 0) g_moved = true;  // already running from %TEMP%
        }
        LocalFree(argv);
    }
    HRESULT hr = CoInitializeEx(nullptr, COINIT_APARTMENTTHREADED);  // shortcut + known folders
    int rc = uninstall ? Uninstall() : Install();
    if (SUCCEEDED(hr)) CoUninitialize();
    return rc;
}
