"""Regenerate app/src/emoji_table.h from the gemoji database.

    python app/tools/gen_emoji.py [path-or-url-to-emoji.json]

The table is what `:shortcode:` substitution in parse.cpp looks names up in: names are ASCII in one blob, the
emoji themselves UTF-16 in another, and the index is sorted by name for a binary search.
"""
import json
import pathlib
import sys
import urllib.request

SRC = "https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json"
OUT = pathlib.Path(__file__).resolve().parents[1] / "src" / "emoji_table.h"

arg = sys.argv[1] if len(sys.argv) > 1 else SRC
raw = pathlib.Path(arg).read_bytes() if not arg.startswith("http") else urllib.request.urlopen(arg).read()
db = json.loads(raw.decode("utf-8"))

pairs = {}
for e in db:
    for alias in e.get("aliases", []):
        if all(c.isalnum() or c in "_+-" for c in alias):
            pairs.setdefault(alias, e["emoji"])
names = sorted(pairs)

name_blob, emoji_blob, index = [], [], []
name_off = emoji_off = 0
for n in names:
    utf16 = pairs[n].encode("utf-16-le")
    index.append((name_off, emoji_off, len(n), len(utf16) // 2))
    name_blob.append(n)
    emoji_blob.append(pairs[n])
    name_off += len(n) + 1
    emoji_off += len(utf16) // 2 + 1


def c_names(chunk):
    return '"' + chunk.replace("\\", "\\\\").replace('"', '\\"') + '\\0"'


def c_emoji(s):
    b = s.encode("utf-16-le")
    return "".join("\\x%04x" % int.from_bytes(b[i:i + 2], "little") for i in range(0, len(b), 2))


lines = ["// Generated by app/tools/gen_emoji.py from the gemoji database - do not edit by hand.",
         f"// {len(names)} shortcodes.", "#pragma once", "#include <cstdint>", "",
         "inline const char kEmojiNames[] ="]
for i in range(0, len(name_blob), 8):
    lines.append("    " + " ".join(c_names(n) for n in name_blob[i:i + 8]))
lines.append("    ;")
lines.append("")
lines.append("inline const wchar_t kEmojiChars[] =")
for i in range(0, len(emoji_blob), 8):
    lines.append("    " + " ".join('L"' + c_emoji(e) + '\\0"' for e in emoji_blob[i:i + 8]))
lines.append("    ;")
lines.append("")
lines.append("struct EmojiEntry { uint32_t name, chars; uint16_t nameLen, charsLen; };")
lines.append(f"inline const EmojiEntry kEmoji[{len(index)}] = {{")
for i in range(0, len(index), 6):
    lines.append("    " + " ".join("{%d,%d,%d,%d}," % e for e in index[i:i + 6]))
lines.append("};")
lines.append("")
OUT.write_text("\n".join(lines), encoding="ascii")
print(f"{OUT}: {len(names)} shortcodes, {OUT.stat().st_size // 1024} KB")
