#include "common.h"
#include "strings.h"

namespace {
struct Pair { const wchar_t* ru; const wchar_t* en; };
const Pair kStr[] = {
    // context menu
    {L"Копировать\tCtrl+C", L"Copy\tCtrl+C"},
    {L"Выделить всё\tCtrl+A", L"Select all\tCtrl+A"},
    {L"Найти…\tCtrl+F", L"Find…\tCtrl+F"},
    {L"Оглавление\tCtrl+Shift+O", L"Outline\tCtrl+Shift+O"},
    {L"Назад\tAlt+←", L"Back\tAlt+←"},
    {L"Вперёд\tAlt+→", L"Forward\tAlt+→"},
    {L"Открыть файл…\tCtrl+O", L"Open file…\tCtrl+O"},
    {L"Обновить\tF5", L"Reload\tF5"},
    {L"Открыть во внешнем редакторе\tCtrl+E", L"Open in external editor\tCtrl+E"},
    {L"Показать в папке", L"Show in folder"},
    {L"Тема", L"Theme"},
    {L"Как в системе", L"System"},
    {L"Светлая", L"Light"},
    {L"Тёмная", L"Dark"},
    {L"Масштаб: %d %%", L"Zoom: %d%%"},
    {L"Увеличить\tCtrl++", L"Zoom in\tCtrl++"},
    {L"Уменьшить\tCtrl+−", L"Zoom out\tCtrl+−"},
    {L"Сбросить (100 %)\tCtrl+0", L"Reset (100%)\tCtrl+0"},
    {L"Ширина колонки", L"Column width"},
    {L"Узкая", L"Narrow"},
    {L"Обычная", L"Normal"},
    {L"Широкая", L"Wide"},
    {L"Во всю ширину", L"Full width"},
    {L"Переносить строки в коде", L"Wrap lines in code"},
    {L"Настройки…\tCtrl+,", L"Settings…\tCtrl+,"},
    {L"Открывать .md в FastMD…", L"Open .md files with FastMD…"},
    {L"Открыть ссылку", L"Open link"},
    {L"Копировать адрес ссылки", L"Copy link address"},
    {L"Копировать картинку", L"Copy image"},
    {L"Открыть файл картинки", L"Open image file"},
    {L"Печать…	Ctrl+P", L"Print…	Ctrl+P"},
    {L"Экспорт в PDF…", L"Export to PDF…"},
    // toasts / messages
    {L"Скопировано", L"Copied"},
    {L"Скопировано как Markdown", L"Copied as Markdown"},
    {L"Копировать как Markdown\tCtrl+Shift+C", L"Copy as Markdown\tCtrl+Shift+C"},
    {L"Код скопирован", L"Code copied"},
    {L"Адрес ссылки скопирован", L"Link address copied"},
    {L"Картинка скопирована", L"Image copied"},
    {L"Обновлено", L"Reloaded"},
    {L"Заголовок не найден: ", L"Heading not found: "},
    {L"Файл не найден: ", L"File not found: "},
    {L"FastMD зарегистрирован. Выберите его для .md в «Приложения по умолчанию»",
     L"FastMD is registered. Choose it for .md in Settings → Default apps"},
    {L"Не удалось записать ассоциацию в реестр", L"Could not write the association to the registry"},
    {L"Ширина колонки: ", L"Column width: "},
    {L"Не удалось запустить редактор", L"Could not start the editor"},
    {L"Документ хочет открыть:\n\n%s\n\nОткрыть?", L"The document wants to open:\n\n%s\n\nOpen it?"},
    {L"Не удалось открыть файл", L"Could not open the file"},
    {L"Строки в коде переносятся", L"Code lines wrap"},
    {L"Строки в коде не переносятся", L"Code lines scroll"},
    {L"Отправлено на печать", L"Sent to the printer"},
    {L"Не удалось напечатать", L"Could not print"},
    {L"PDF сохранён", L"PDF saved"},
    {L"Не найден принтер «Microsoft Print to PDF»", L"The Microsoft Print to PDF printer was not found"},
    {L"%d из %d", L"%d of %d"},
    {L"Прошлый запуск FastMD завершился ошибкой. Отчёт сохранён:\n\n%s\n\nОткрыть папку с отчётом?",
     L"The last run of FastMD ended with an error. The report was saved:\n\n%s\n\nOpen the folder?"},
    {L"Доступна версия ", L"Version available: "},
    {L"Обновить FastMD до версии %s?\n\nСейчас установлена %s. Установщик скачается с GitHub и проверится по хешу из того же выпуска.",
     L"Update FastMD to version %s?\n\nYou have %s. The installer is downloaded from GitHub and checked against the hash published with the same release."},
    {L"Загружаю обновление…", L"Downloading the update…"},
    {L"Устанавливаю обновление…", L"Installing the update…"},
    {L"Не удалось загрузить обновление", L"The update could not be downloaded"},
    {L"Обновить FastMD…", L"Update FastMD…"},
    {L"Файл занят другой программой — отметка не сохранена",
     L"Another program is using the file — the tick was not saved"},
    {L"Файл защищён от записи — отметка не сохранена", L"The file is write-protected — the tick was not saved"},
    {L"Файл изменился на диске — документ обновлён, отметьте ещё раз",
     L"The file changed on disk — reloaded, click the box again"},
    {L"Не удалось сохранить отметку в файл", L"Could not save the tick to the file"},
    // find bar
    {L"Найти в документе", L"Find in document"},
    {L"нет совпадений", L"no results"},
    {L"Учитывать регистр (Alt+C)", L"Match case (Alt+C)"},
    {L"Слово целиком (Alt+W)", L"Whole word (Alt+W)"},
    {L"Предыдущее (Shift+Enter)", L"Previous (Shift+Enter)"},
    {L"Следующее (Enter)", L"Next (Enter)"},
    {L"Закрыть (Esc)", L"Close (Esc)"},
    // start screen
    {L"Откройте Markdown-файл", L"Open a Markdown file"},
    {L"Перетащите .md сюда или нажмите Ctrl+O", L"Drop a .md file here or press Ctrl+O"},
    {L"Недавние документы", L"Recent documents"},
    {L"Поиск по названию", L"Search by name"},
    {L"Ничего не найдено", L"Nothing found"},
    // outline
    {L"Оглавление", L"Outline"},
    {L"В документе нет заголовков", L"This document has no headings"},
    {L"Оглавление (Ctrl+Shift+O)", L"Outline (Ctrl+Shift+O)"},
    // settings window
    {L"Настройки FastMD", L"FastMD Settings"},
    {L"Настройки (Ctrl+,)", L"Settings (Ctrl+,)"},
    {L"Тема", L"Theme"},
    {L"Шрифт текста", L"Text font"},
    {L"Segoe UI", L"Segoe UI"},
    {L"Sitka (книжный)", L"Sitka (book)"},
    {L"Размер текста", L"Text size"},
    {L"Ширина колонки", L"Column width"},
    {L"Переносить строки в коде", L"Wrap lines in code"},
    {L"Выкл", L"Off"},
    {L"Вкл", L"On"},
    {L"Плавная прокрутка", L"Smooth scrolling"},
    {L"Редактор для Ctrl+E", L"Editor for Ctrl+E"},
    {L"Как в системе", L"System default"},
    {L"Блокнот", L"Notepad"},
    {L"Другой…", L"Other…"},
    {L"Язык интерфейса", L"Language"},
    {L"Как в системе", L"System"},
    {L"Файлы .md", L".md files"},
    {L"Открывать .md в FastMD…", L"Open .md files with FastMD…"},
    {L"FastMD %s · лицензия GPL-3.0", L"FastMD %s · GPL-3.0 license"},
    {L"Картинки из сети", L"Pictures from the web"},
    {L"Всегда", L"Always"},
    {L"Спрашивать", L"Ask"},
    {L"Никогда", L"Never"},
    {L"Загрузить картинки из сети", L"Load pictures from the web"},
    {L"Картинки из сети не загружены", L"Pictures from the web were not loaded"},
    {L"Проверять обновления", L"Check for updates"},
    // updater
    {L" — обновить можно в настройках", L" — update from the settings"},
    {L"Не удалось проверить обновления: GitHub не ответил", L"Could not check for updates: GitHub did not answer"},
    {L"У вас последняя версия FastMD", L"FastMD is up to date"},
    {L"Установщик обновления завершился с ошибкой", L"The update installer failed"},
    {L"FastMD %s установлен.\n\nПерезапустить FastMD сейчас? Документ откроется на том же месте.",
     L"FastMD %s is installed.\n\nRestart FastMD now? The document reopens at the same place."},
    {L"Настройки (Ctrl+,) — доступно обновление ", L"Settings (Ctrl+,) — update available: "},
    {L"Обновление", L"Update"},
    {L"Проверить сейчас", L"Check now"},
    {L"Проверяю…", L"Checking…"},
    {L"Обновить до %s", L"Update to %s"},
    {L"Загружаю…", L"Downloading…"},
    {L"Устанавливаю…", L"Installing…"},
    {L"Перезапустить", L"Restart"},
    {L"сейчас установлена %s", L"you have %s"},
    {L"%s — последняя версия", L"%s is the latest version"},
    {L"GitHub не ответил", L"GitHub did not answer"},
    {L"%s установлена — перезапустите", L"%s is installed — restart"},
    {L"не удалось загрузить или установить", L"could not download or install"},
    // shell
    {L"Markdown (*.md; *.markdown; *.mdx; *.txt)", L"Markdown (*.md; *.markdown; *.mdx; *.txt)"},
    {L"Все файлы", L"All files"},
    {L"Программы (*.exe)", L"Programs (*.exe)"},
    {L"Документ PDF (*.pdf)", L"PDF document (*.pdf)"},
    {L"Markdown-документ", L"Markdown document"},
    {L"Мгновенный просмотр Markdown", L"Instant Markdown reader"},
    // edit mode
    {L"Правка отклонена", L"Edit refused"},
    {L"Прошлое сохранение прервалось", L"The last save was interrupted"},
    {L"Открыть копию", L"Open the copy"},
    {L"Восстановить", L"Restore"},
    {L"Удалить", L"Delete"},
    {L"Не удалось восстановить файл", L"The file could not be restored"},
    {L" (восстановлено)", L" (recovered)"},
    {L"Прошлое сохранение прервалось, а файл с тех пор изменён", L"The last save was interrupted, and the file has changed since"},
    // edit mode, phase 2a: toolbar tooltips
    {L"Отменить", L"Undo"},
    {L"Повторить", L"Redo"},
    {L"Стиль абзаца", L"Paragraph style"},
    {L"Полужирный", L"Bold"},
    {L"Курсив", L"Italic"},
    {L"Зачёркнутый", L"Strikethrough"},
    {L"Код в строке", L"Inline code"},
    {L"Ссылка", L"Link"},
    {L"Маркированный список", L"Bulleted list"},
    {L"Нумерованный список", L"Numbered list"},
    {L"Список задач", L"Task list"},
    {L"Цитата", L"Quote"},
    {L"Блок кода", L"Code block"},
    {L"Таблица", L"Table"},
    {L"Формула", L"Formula"},
    {L"Диаграмма", L"Diagram"},
    {L"Изображение", L"Image"},
    {L"Горизонтальная линия", L"Horizontal rule"},
    {L"Ещё", L"More"},
    {L"Закончить редактирование", L"Finish editing"},
    // style labels
    {L"Текст", L"Text"},
    {L"Заголовок %d", L"Heading %d"},
    {L"Код", L"Code"},
    {L"Таблица", L"Table"},
    {L"Сноска", L"Footnote"},
    // the status slot
    {L"Сохранено", L"Saved"},
    {L"Не сохранено", L"Not saved"},
    {L"Сохранение…", L"Saving…"},
    {L"Не сохранено: файл занят", L"Not saved: the file is busy"},
    {L"Не сохранено: нет доступа", L"Not saved: access denied"},
    {L"Не сохранено: файла нет", L"Not saved: the file is gone"},
    {L"Не сохранено: конфликт", L"Not saved: conflict"},
    {L"Не сохранено: кодировка", L"Not saved: encoding"},
    {L"Не сохранено: файл недоступен", L"Not saved: file unavailable"},
    {L"Не сохранено: ошибка записи", L"Not saved: write error"},
    {L"Не сохранено (Ctrl+S)", L"Not saved (Ctrl+S)"},
    {L"Прежние байты файла сохранены в %s", L"The previous bytes of the file are kept in %s"},
    // why a save failed
    {L"файл занят", L"the file is busy"},
    {L"нет доступа", L"access denied"},
    {L"файла нет", L"the file is gone"},
    {L"файл изменён другой программой", L"the file was changed by another program"},
    {L"кодировка", L"encoding"},
    {L"файл недоступен", L"file unavailable"},
    {L"ошибка записи", L"write error"},
    // entering, toasts
    {L"Редактировать (F2 или двойной щелчок)", L"Edit (F2 or double-click)"},
    {L"Режим правки: Esc — выйти, F2 — войти снова", L"Edit mode: Esc — leave, F2 — enter again"},
    {L"Правки сохраняются в файл автоматически · Ctrl+Z — отменить",
     L"Edits are saved to the file automatically · Ctrl+Z — undo"},
    {L"Файл не загрузился — править нечего", L"The file did not load — nothing to edit"},
    {L"Документ ещё загружается…", L"The document is still loading…"},
    {L"Нет папки данных FastMD — правка отключена", L"No FastMD data folder — editing is off"},
    {L"Не удалось прочитать файл: %s", L"Could not read the file: %s"},
    {L"Файл похож на двоичный — правка отключена", L"The file looks binary — editing is off"},
    {L"UTF-16 BE не поддерживается для правки", L"UTF-16 BE files cannot be edited"},
    {L"Файл UTF-16 повреждён (нечётная длина)", L"The UTF-16 file is damaged (odd length)"},
    {L"Кодировку файла нельзя сохранить без потерь — правка отключена",
     L"This file's encoding cannot be saved without loss — editing is off"},
    {L"Файл занят — сохраню, как только он освободится", L"The file is busy — it will be saved as soon as it is free"},
    {L"Файл изменён другой программой — загружена новая версия",
     L"The file was changed by another program — the new version is loaded"},
    {L"История правок сброшена: текст изменился", L"Undo history reset: the text changed"},
    {L"Delete — удалить · ←/→ — выйти", L"Delete — delete · ←/→ — leave"},  // (Enter opens the source from 3b on)
    // strips
    {L"Файл изменён другой программой (на диске: %s, у вас: %s).",
     L"The file was changed by another program (on disk: %s, yours: %s)."},
    {L"Загрузить версию с диска (мои правки отменятся)", L"Load the disk version (discard mine)"},
    {L"Перезаписать файл моими правками", L"Overwrite the file with my edits"},
    {L"Символ «%s» нельзя сохранить в кодировке %s.", L"The character “%s” cannot be saved in the %s encoding."},
    {L"Сохранять в UTF-8", L"Save as UTF-8"},
    {L"Убрать символ", L"Remove the character"},
    {L"Файл не может так начинаться: начало примут за метку кодировки.",
     L"The file cannot start like this: its start would be read as a byte-order mark."},
    {L"Правки не сохранены: %s.", L"Edits are not saved: %s."},
    {L"Повторить", L"Retry"},
    {L"Сохранить как…", L"Save as…"},
    {L"Отменить правки", L"Discard edits"},
    {L"Файл только для чтения — правки нельзя сохранить в него.", L"The file is read-only — edits cannot be saved to it."},
    {L"Файл удалён или переименован.", L"The file was deleted or renamed."},
    {L"Есть несохранённые правки от %s", L"There are unsaved edits from %s"},
    {L" (несохранённые правки)", L" (unsaved edits)"},
    {L"Файл уже редактируется в другом окне FastMD.", L"This file is already being edited in another FastMD window."},
    {L"Перейти к нему", L"Go to it"},
    {L"Только чтение", L"Read only"},
    // leaving the document, Save As
    {L"Правки в «%s» не сохранены: %s.\n\nСохранить их в другой файл?",
     L"The edits to “%s” are not saved: %s.\n\nSave them to another file?"},
    {L"Правки в «%s» не сохранены: %s.\n\nПопробовать сохранить ещё раз?",
     L"The edits to “%s” are not saved: %s.\n\nTry to save them again?"},
    {L"Файл «%s» изменён другой программой, а ваши правки не сохранены.\n\nПерезаписать файл вашими правками?",
     L"“%s” was changed by another program, and your edits are not saved.\n\nOverwrite the file with your edits?"},
    {L"Сохранить ваши правки в другой файл?", L"Save your edits to another file?"},
    {L"Символ «%s» нельзя сохранить в кодировке %s.\n\nСохранить файл в UTF-8?",
     L"The character “%s” cannot be saved in the %s encoding.\n\nSave the file as UTF-8?"},
    {L"Относительные ссылки и картинки (%d) перестанут работать в новой папке. Сохранить всё равно?",
     L"%d relative links and pictures will stop working in the new folder. Save anyway?"},
    // context menus, settings, sizes
    {L"Редактировать здесь\tF2", L"Edit here\tF2"},
    {L"Отменить\tCtrl+Z", L"Undo\tCtrl+Z"},
    {L"Повторить\tCtrl+Y", L"Redo\tCtrl+Y"},
    {L"Вырезать\tCtrl+X", L"Cut\tCtrl+X"},
    {L"Вставить\tCtrl+V", L"Paste\tCtrl+V"},
    {L"Открыть ссылку\tCtrl+щелчок", L"Open link\tCtrl+click"},
    {L"Сохранить\tCtrl+S", L"Save\tCtrl+S"},
    {L"Сохранить как…", L"Save as…"},
    {L"Закончить редактирование\tEsc", L"Finish editing\tEsc"},
    {L"Автосохранение правок", L"Autosave edits"},
    {L"%u Б", L"%u B"},
    {L"%.1f КБ", L"%.1f KB"},
    {L"%.1f МБ", L"%.1f MB"},
    // the review of 2a
    {L"Сначала решите, что делать с прерванным сохранением (полоса сверху)",
     L"First decide what to do with the interrupted save (the strip above)"},
};
static_assert(std::size(kStr) == S_COUNT, "one entry per StrId");
UiLang g_lang = UL_RU;
}  // namespace

void SetUiLanguage(UiLang l) { g_lang = l; }
UiLang UiLanguage() { return g_lang; }
UiLang SystemUiLanguage() { return PRIMARYLANGID(GetUserDefaultUILanguage()) == LANG_RUSSIAN ? UL_RU : UL_EN; }
const wchar_t* Tr(StrId id) { return id < S_COUNT ? (g_lang == UL_RU ? kStr[id].ru : kStr[id].en) : L""; }
