// UI strings, Russian and English. The language is resolved once (settings: auto → the user's UI language).
#pragma once
#include <cstdint>

enum StrId : uint16_t {
    // context menu
    S_MENU_COPY, S_MENU_SELECT_ALL, S_MENU_FIND, S_MENU_TOC, S_MENU_BACK, S_MENU_FORWARD, S_MENU_OPEN, S_MENU_RELOAD,
    S_MENU_EDIT, S_MENU_FOLDER, S_MENU_THEME, S_THEME_SYSTEM, S_THEME_LIGHT, S_THEME_DARK, S_MENU_ZOOM_FMT, S_ZOOM_IN,
    S_ZOOM_OUT, S_ZOOM_RESET, S_MENU_COLUMN, S_COL_NARROW, S_COL_NORMAL, S_COL_WIDE, S_COL_FULL, S_MENU_WRAP,
    S_MENU_SETTINGS, S_MENU_ASSOCIATE, S_LINK_OPEN, S_LINK_COPY, S_IMG_COPY, S_IMG_OPEN, S_MENU_PRINT, S_MENU_PDF,
    // toasts / messages
    S_COPIED, S_COPIED_MD, S_MENU_COPY_MD, S_CODE_COPIED, S_LINK_COPIED, S_IMG_COPIED, S_RELOADED, S_HEADING_NOT_FOUND, S_FILE_NOT_FOUND, S_ASSOC_OK,
    S_ASSOC_FAIL, S_COLUMN_TOAST, S_EDITOR_FAIL, S_CONFIRM_OPEN, S_LOAD_FAILED, S_WRAP_ON, S_WRAP_OFF,
    S_PRINTED, S_PRINT_FAILED, S_PDF_SAVED, S_PDF_NO_PRINTER, S_PRINT_PAGE_FMT,
    // find bar
    S_FIND_PLACEHOLDER, S_FIND_NONE, S_FIND_CASE_TIP, S_FIND_WORD_TIP, S_FIND_PREV_TIP, S_FIND_NEXT_TIP, S_FIND_CLOSE_TIP,
    // start screen
    S_EMPTY_TITLE, S_EMPTY_HINT, S_RECENT_TITLE, S_RECENT_FILTER, S_RECENT_NONE,
    // outline
    S_TOC_TITLE, S_TOC_EMPTY, S_TOC_BUTTON_TIP,
    // settings window
    S_SETTINGS_TITLE, S_SETTINGS_BUTTON_TIP, S_SET_THEME, S_SET_FONT, S_FONT_SEGOE, S_FONT_SITKA, S_SET_SIZE, S_SET_COLUMN, S_SET_WRAP, S_OFF,
    S_ON, S_SET_SMOOTH, S_SET_EDITOR, S_EDITOR_SYSTEM, S_EDITOR_NOTEPAD, S_EDITOR_OTHER, S_SET_LANGUAGE, S_LANG_SYSTEM,
    S_SET_ASSOC, S_SET_ASSOC_BTN, S_SET_ABOUT,
    S_SET_REMOTE, S_REMOTE_ALWAYS, S_REMOTE_ASK, S_REMOTE_NEVER, S_MENU_LOAD_REMOTE, S_REMOTE_BLOCKED,
    // shell
    S_FILTER_MD, S_FILTER_ALL, S_FILTER_EXE, S_FILTER_PDF, S_PROGID_NAME, S_APP_DESCRIPTION,
    S_COUNT
};

enum UiLang : uint8_t { UL_RU = 0, UL_EN = 1 };

void SetUiLanguage(UiLang l);
UiLang UiLanguage();
UiLang SystemUiLanguage();  // Russian for a Russian Windows UI, English otherwise
const wchar_t* Tr(StrId id);
