// UI strings, Russian and English. The language is resolved once (settings: auto → the user's UI language).
#pragma once
#include <cstdint>

enum StrId : uint16_t {
    // context menu
    S_MENU_COPY, S_MENU_SELECT_ALL, S_MENU_FIND, S_MENU_TOC, S_MENU_BACK, S_MENU_FORWARD, S_MENU_OPEN, S_MENU_RELOAD,
    S_MENU_EDIT, S_MENU_FOLDER, S_MENU_THEME, S_THEME_SYSTEM, S_THEME_LIGHT, S_THEME_DARK, S_MENU_ZOOM_FMT, S_ZOOM_IN,
    S_ZOOM_OUT, S_ZOOM_RESET, S_MENU_COLUMN, S_COL_NARROW, S_COL_NORMAL, S_COL_WIDE, S_COL_FULL, S_MENU_WRAP,
    S_MENU_SETTINGS, S_MENU_ASSOCIATE, S_LINK_OPEN, S_LINK_COPY, S_IMG_COPY, S_IMG_OPEN, S_MENU_PRINT, S_MENU_PDF,
    // toasts / messages
    S_COPIED, S_COPIED_MD, S_MENU_COPY_MD, S_CODE_COPIED, S_LINK_COPIED, S_IMG_COPIED, S_RELOADED, S_HEADING_NOT_FOUND, S_FILE_NOT_FOUND, S_ASSOC_OK,
    S_ASSOC_FAIL, S_COLUMN_TOAST, S_EDITOR_FAIL, S_CONFIRM_OPEN, S_LOAD_FAILED, S_WRAP_ON, S_WRAP_OFF,
    S_PRINTED, S_PRINT_FAILED, S_PDF_SAVED, S_PDF_NO_PRINTER, S_PRINT_PAGE_FMT, S_CRASH_FOUND,
    S_UPDATE_FOUND, S_UPDATE_CONFIRM, S_UPDATE_DOWNLOADING, S_UPDATE_INSTALLING, S_UPDATE_FAILED,
    S_MENU_UPDATE, S_TASK_BUSY, S_TASK_DENIED, S_TASK_CHANGED, S_TASK_FAILED,
    // find bar
    S_FIND_PLACEHOLDER, S_FIND_NONE, S_FIND_CASE_TIP, S_FIND_WORD_TIP, S_FIND_PREV_TIP, S_FIND_NEXT_TIP, S_FIND_CLOSE_TIP,
    // start screen
    S_EMPTY_TITLE, S_EMPTY_HINT, S_RECENT_TITLE, S_RECENT_FILTER, S_RECENT_NONE,
    // outline
    S_TOC_TITLE, S_TOC_EMPTY, S_TOC_BUTTON_TIP,
    // settings window
    S_SETTINGS_TITLE, S_SETTINGS_BUTTON_TIP, S_SET_THEME, S_SET_FONT, S_FONT_SEGOE, S_FONT_SITKA, S_SET_SIZE, S_SET_COLUMN, S_SET_WRAP, S_OFF,
    S_ON, S_SET_SMOOTH, S_SET_EDITOR, S_EDITOR_SYSTEM, S_EDITOR_NOTEPAD, S_EDITOR_OTHER, S_SET_LANGUAGE, S_LANG_SYSTEM,
    S_SET_ASSOC, S_SET_ASSOC_BTN, S_SET_ABOUT,
    S_SET_REMOTE, S_REMOTE_ALWAYS, S_REMOTE_ASK, S_REMOTE_NEVER, S_MENU_LOAD_REMOTE, S_REMOTE_BLOCKED,
    S_SET_UPDATE,
    // updater
    S_UPDATE_FOUND_HINT, S_UPDATE_CHECK_FAILED, S_UPDATE_LATEST, S_UPDATE_INSTALL_FAILED, S_UPDATE_RESTART_ASK,
    S_SETTINGS_BUTTON_UPDATE_TIP, S_SET_VERSION, S_UPD_CHECK, S_UPD_CHECKING, S_UPD_UPDATE_FMT, S_UPD_DOWNLOADING,
    S_UPD_INSTALLING, S_UPD_RESTART, S_UPD_NOTE_CURRENT_FMT, S_UPD_NOTE_LATEST_FMT, S_UPD_NOTE_FAILED,
    S_UPD_NOTE_INSTALLED_FMT, S_UPD_NOTE_DL_FAILED,
    // shell
    S_FILTER_MD, S_FILTER_ALL, S_FILTER_EXE, S_FILTER_PDF, S_PROGID_NAME, S_APP_DESCRIPTION,
    // edit mode (docs/EDIT-MODE.md Appendix A): one S_ED_* group, appended to as the phases arrive
    S_ED_REFUSED, S_ED_RECOVERY_INTERRUPTED, S_ED_RECOVERY_OPEN, S_ED_RECOVERY_RESTORE, S_ED_RECOVERY_DELETE,
    S_ED_RECOVERY_FAILED, S_ED_RECOVERED, S_ED_RECOVERY_CHANGED,
    // Phase 2a: the toolbar's tooltips (§2.3), the style labels, the status slot (§2.6), the reasons a save failed
    S_ED_TIP_UNDO, S_ED_TIP_REDO, S_ED_TIP_STYLE, S_ED_TIP_BOLD, S_ED_TIP_ITALIC, S_ED_TIP_STRIKE, S_ED_TIP_CODE,
    S_ED_TIP_LINK, S_ED_TIP_BULLET, S_ED_TIP_NUMBER, S_ED_TIP_TASK, S_ED_TIP_QUOTE, S_ED_TIP_CODEBLOCK, S_ED_TIP_TABLE,
    S_ED_TIP_FORMULA, S_ED_TIP_DIAGRAM, S_ED_TIP_IMAGE, S_ED_TIP_HR, S_ED_TIP_MORE, S_ED_TIP_EXIT,
    S_ED_STYLE_TEXT, S_ED_STYLE_HEADING_FMT, S_ED_STYLE_CODE, S_ED_STYLE_TABLE, S_ED_STYLE_FOOTNOTE,
    S_ED_ST_SAVED, S_ED_ST_PENDING, S_ED_ST_SAVING, S_ED_ST_BUSY, S_ED_ST_DENIED, S_ED_ST_MISSING, S_ED_ST_CONFLICT,
    S_ED_ST_ENCODING, S_ED_ST_UNKNOWN, S_ED_ST_FAILED, S_ED_ST_OFF, S_ED_ST_RECOVERY_FMT,
    S_ED_WHY_BUSY, S_ED_WHY_DENIED, S_ED_WHY_MISSING, S_ED_WHY_CONFLICT, S_ED_WHY_ENCODING, S_ED_WHY_UNKNOWN,
    S_ED_WHY_FAILED,
    // entering (§2.1), toasts
    S_ED_PENCIL_TIP, S_ED_HINT_FIRST, S_ED_HINT_AUTOSAVE, S_ED_NO_LOAD, S_ED_LOADING, S_ED_NO_DATADIR, S_ED_NO_READ_FMT,
    S_ED_BINARY, S_ED_UTF16BE, S_ED_UTF16ODD, S_ED_LOSSY, S_ED_BUSY_TOAST, S_ED_ADOPTED, S_ED_UNDO_RESET, S_ED_ATOM_HINT,
    // strips (§2.5)
    S_ED_CONFLICT_FMT, S_ED_CONFLICT_LOAD, S_ED_CONFLICT_KEEP, S_ED_ENCODING_FMT, S_ED_ENC_UTF8, S_ED_ENC_REMOVE,
    S_ED_BOM_LOOKALIKE, S_ED_LEAVE_FMT, S_ED_RETRY, S_ED_SAVE_AS_BTN, S_ED_DISCARD, S_ED_READONLY, S_ED_MISSING,
    S_ED_JOURNAL_FMT, S_ED_JOURNAL_COPY, S_ED_OTHER_WINDOW, S_ED_GO_TO_IT, S_ED_READ_ONLY_BTN,
    // leaving the document (§10.8), Save As (§10.7)
    S_ED_ASK_SAVE_AS_FMT, S_ED_ASK_RETRY_FMT, S_ED_ASK_CONFLICT_FMT, S_ED_ASK_CONFLICT2, S_ED_ASK_UTF8_FMT,
    S_ED_ASK_RELLINKS_FMT,
    // context menus (§2.9), the settings row (§2.12), sizes
    S_MENU_EDIT_HERE, S_ED_MENU_UNDO, S_ED_MENU_REDO, S_ED_MENU_CUT, S_ED_MENU_PASTE, S_ED_MENU_OPEN_LINK,
    S_ED_MENU_SAVE, S_ED_MENU_SAVE_AS, S_ED_MENU_EXIT, S_SET_AUTOSAVE, S_ED_SIZE_B, S_ED_SIZE_KB, S_ED_SIZE_MB,
    // the review of 2a: entry waits for the recovery strip's decision (§10.5)
    S_ED_RECOVERY_FIRST,
    S_COUNT
};

enum UiLang : uint8_t { UL_RU = 0, UL_EN = 1 };

void SetUiLanguage(UiLang l);
UiLang UiLanguage();
UiLang SystemUiLanguage();  // Russian for a Russian Windows UI, English otherwise
const wchar_t* Tr(StrId id);
